### ISSUE TITLE
What happened to nlinum-relative?

### ISSUE THREAD

**Issue by joe9** [coldnew/linum-relative#13]
Hello,

This is not a linum-relative issue but I could not figure out how to ask you this question. I use nlinum and noticed that you had a nlinum-relative repository. https://github.com/edran/emacs.d/blob/master/lisp/nlinum-relative.el

Just want to check your thoughts on why you still do not have a nlinum-relative repo?

Thanks
Joe

**Comment by coldnew** [comment]
Sorry, I can't recall I have a nlinum-relative.el, the first version of linum-relative.el is since 2012. I don't know what's wrong.

I have take a look at nlinum-relative.el you provide, all function compatible with linum-relative.el, you just need to change the function name.

Anyway, use linum-relative.el replace nlinum-relative.el.
