### ISSUE TITLE
linum-relative-current-symbol should not be displayed in Evil mode in command-line

### ISSUE THREAD

**Issue by chumakd** [coldnew/linum-relative#38]
Evil mode emulates Vim command line feature (accessible by `:` key).  If _linum-relative-global-mode_ mode is enabled, the _linum-relative-current-symbol_ (defaults to `0`) is displayed when command-line is active.

<img width="221" alt="screen shot 2017-01-19 at 12 05 58 pm" src="https://cloud.githubusercontent.com/assets/1629650/22094478/3caeeb22-de40-11e6-9935-e2fa5e78b60b.png">

**Comment by coldnew** [comment]
Not sure what happend :(  

Since linum-relative is based on `linum-mode`, can you make sure linum-mode won't display on `minibuffer` ?

<img width="658" alt="screen shot 2017-01-19 at 1 38 49 pm" src="https://cloud.githubusercontent.com/assets/39703/22095077/f24d9a1c-de4c-11e6-9189-7675837b1063.png">

**Comment by chumakd** [comment]
Thanks for the tip. After adding `(add-hook 'minibuffer-setup-hook (lambda () (linum-mode 0)))` the issue has gone.

**Comment by coldnew** [comment]
Since `linum-mode` will make emacs slow on large file, it's more recommend to use [linum-off](http://melpa.org/#/linum-off) with any `linum-mode` based plugins.

[linum-off](http://melpa.org/#/linum-off) will disable `linum-mode` on the minibuffer by default.
